# Copied from https://circleci.com/docs/2.0/language-javascript/
version: 2.1
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
      - image: circleci/mongo:4.2.0 # and this image as the secondary service container
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test-and-coverage
          command: npm run coverage
      - store_artifacts:
          path: coverage/lcov-report
          prefix: coverage
